#! /bin/bash

source /usr/lib/naylib

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

draw_heading "Update packages (native)"

distro_name=$(lsb_release -i | sed 's/.*:\s*//g')
case "$distro_name" in
Arch)
  draw_spinner "Updating mirror list" "sudo reflector --verbose --latest 10 --sort rate --save /etc/pacman.d/mirrorlist"
  yay -Syu --sudoloop --noconfirm
  ;;
Ubuntu)
  sudo apt update && sudo apt upgrade
  ;;
esac

draw_heading "Update packages (uur)"
uur update
uur upgrade
pkill -RTMIN+3 dwmblocks

draw_heading "Sync packages"
# Characters to alternate
chars=('|' '/' '-' '\')
i=0
echo -ne "${chars[i % 2]}\r"
((i++))
sudo -v
# TODO merge loops
for pkg in $(cat "$DIR/../packages" | sed -e '/^[ \t]*#/d' | sed '/^$/d'); do
  uur native "$pkg" "Installing"
  sudo -v &
  # Print alternating character
  echo -ne "${chars[i % 4]}\r"
  ((i++))
done
for pkg in $(cat "$DIR/../packages_${distro_name}" | sed -e '/^[ \t]*#/d' | sed '/^$/d'); do
  uur native "$pkg" "Installing"
  sudo -v &
  # Print alternating character
  echo -ne "${chars[i % 4]}\r"
  ((i++))
done
