#! /bin/bash

source /usr/lib/naylib

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

draw_heading "Install packages"

draw_spinner "Updating mirror list" "sudo reflector --verbose --latest 10 --sort rate --save /etc/pacman.d/mirrorlist"

yay -Syu --sudoloop --noconfirm
pkill -RTMIN+3 dwmblocks

for pkg in `cat "$DIR/../packages" | sed -e '/^[ \t]*#/d' | sed '/^$/d'` ; do
  sudo -v
  if ! yay -Sqg "$pkg" &> /dev/null ; then
    yay -Q "$pkg" &> /dev/null && continue
    draw_spinner "Installing $pkg" "yay -S --noconfirm --needed --noredownload --answerclean --sudoloop "$pkg""
  else
    for gpkg in `yay -Sqg "$pkg"` ; do
      yay -Q "$gpkg" &> /dev/null && continue
      draw_spinner "Installing $pkg" "yay -S --noconfirm --needed --noredownload --answerclean --sudoloop "$gpkg""
    done
  fi
done
