#! /bin/bash

source /usr/lib/naylib

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

yay -v &> /dev/null
if [ $? -ne 0 ] ; then
  draw_heading 3 "Install yay"
  sudo pacman -Syu
  sudo pacman -S --noconfirm --needed git base-devel 
  git config --global pull.rebase true
  cd /tmp
  git clone https://aur.archlinux.org/yay.git
  cd yay
  makepkg -si
  echo
  yay -S reflector
fi

draw_heading 3 "Install packages"

draw_spinner "Updating mirror list" "sudo reflector --verbose --latest 10 --sort rate --save /etc/pacman.d/mirrorlist"

yay -Syu --noconfirm

for pkg in `cat "$DIR/../packages" | sed -e '/^[ \t]*#/d' | sed '/^$/d'` ; do
  if ! yay -Q "$pkg" &> /dev/null ; then
    if ! yay -Qg "$pkg" &> /dev/null ; then
      yay -S --noconfirm --needed --noredownload --answerclean --sudoloop "$pkg"
    fi
  fi
done
